/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

BEGIN TRY

	DECLARE @UserName AS TABLE
	(
		[Name] VARCHAR(100)
	)

	INSERT INTO @UserName ([Name])
	
	SELECT Pom.[Name]
	FROM
	(
		SELECT 'Ada' AS [Name] UNION ALL
		SELECT 'Adamina' AS [Name] UNION ALL
		SELECT 'Adela' AS [Name] UNION ALL
		SELECT 'Adelajda' AS [Name] UNION ALL
		SELECT 'Adriana' AS [Name] UNION ALL
		SELECT 'Adrianna' AS [Name] UNION ALL
		SELECT 'Agata' AS [Name] UNION ALL
		SELECT 'Agnieszka' AS [Name] UNION ALL
		SELECT 'Aida' AS [Name] UNION ALL
		SELECT 'Alberta' AS [Name] UNION ALL
		SELECT 'Albertyna' AS [Name] UNION ALL
		SELECT 'Albina' AS [Name] UNION ALL
		SELECT 'Aldona' AS [Name] UNION ALL
		SELECT 'Aleksa' AS [Name] UNION ALL
		SELECT 'Aleksandra' AS [Name] UNION ALL
		SELECT 'Aleksja' AS [Name] UNION ALL
		SELECT 'Alfreda' AS [Name] UNION ALL
		SELECT 'Alicja' AS [Name] UNION ALL
		SELECT 'Alina' AS [Name] UNION ALL
		SELECT 'Alojza' AS [Name] UNION ALL
		SELECT 'Amalia' AS [Name] UNION ALL
		SELECT 'Amanda' AS [Name] UNION ALL
		SELECT 'Amelia' AS [Name] UNION ALL
		SELECT 'Amina' AS [Name] UNION ALL
		SELECT 'Amira' AS [Name] UNION ALL
		SELECT 'Anastazja' AS [Name] UNION ALL
		SELECT 'Andrea' AS [Name] UNION ALL
		SELECT 'Andrzeja' AS [Name] UNION ALL
		SELECT 'Andżelika' AS [Name] UNION ALL
		SELECT 'Aneta' AS [Name] UNION ALL
		SELECT 'Angela' AS [Name] UNION ALL
		SELECT 'Angelika' AS [Name] UNION ALL
		SELECT 'Angelina' AS [Name] UNION ALL
		SELECT 'Aniela' AS [Name] UNION ALL
		SELECT 'Anita' AS [Name] UNION ALL
		SELECT 'Anna' AS [Name] UNION ALL
		SELECT 'Antonina' AS [Name] UNION ALL
		SELECT 'Anzelma' AS [Name] UNION ALL
		SELECT 'Apollina' AS [Name] UNION ALL
		SELECT 'Apolonia' AS [Name] UNION ALL
		SELECT 'Arabella' AS [Name] UNION ALL
		SELECT 'Ariadna' AS [Name] UNION ALL
		SELECT 'Arleta' AS [Name] UNION ALL
		SELECT 'Arnolda' AS [Name] UNION ALL
		SELECT 'Astryda' AS [Name] UNION ALL
		SELECT 'Atena' AS [Name] UNION ALL
		SELECT 'Augusta' AS [Name] UNION ALL
		SELECT 'Augustyna' AS [Name] UNION ALL
		SELECT 'Aurelia' AS [Name] UNION ALL
		SELECT 'B' AS [Name] UNION ALL
		SELECT 'Babeta' AS [Name] UNION ALL
		SELECT 'Balbina' AS [Name] UNION ALL
		SELECT 'Barbara' AS [Name] UNION ALL
		SELECT 'Bartłomieja' AS [Name] UNION ALL
		SELECT 'Beata' AS [Name] UNION ALL
		SELECT 'Beatrycja' AS [Name] UNION ALL
		SELECT 'Beatrycze' AS [Name] UNION ALL
		SELECT 'Beatryksa' AS [Name] UNION ALL
		SELECT 'Benedykta' AS [Name] UNION ALL
		SELECT 'Beniamina' AS [Name] UNION ALL
		SELECT 'Benigna' AS [Name] UNION ALL
		SELECT 'Berenika' AS [Name] UNION ALL
		SELECT 'Bernarda' AS [Name] UNION ALL
		SELECT 'Bernadeta' AS [Name] UNION ALL
		SELECT 'Berta' AS [Name] UNION ALL
		SELECT 'Betina' AS [Name] UNION ALL
		SELECT 'Bianka' AS [Name] UNION ALL
		SELECT 'Bibiana' AS [Name] UNION ALL
		SELECT 'Blanka' AS [Name] UNION ALL
		SELECT 'Błażena' AS [Name] UNION ALL
		SELECT 'Bogdana' AS [Name] UNION ALL
		SELECT 'Bogna' AS [Name] UNION ALL
		SELECT 'Boguchwała' AS [Name] UNION ALL
		SELECT 'Bogumiła' AS [Name] UNION ALL
		SELECT 'Bogusława' AS [Name] UNION ALL
		SELECT 'Bojana' AS [Name] UNION ALL
		SELECT 'Bolesława' AS [Name] UNION ALL
		SELECT 'Bona' AS [Name] UNION ALL
		SELECT 'Bożena' AS [Name] UNION ALL
		SELECT 'Bromira' AS [Name] UNION ALL
		SELECT 'Bronisława' AS [Name] UNION ALL
		SELECT 'Brunhilda' AS [Name] UNION ALL
		SELECT 'Brygida' AS [Name] UNION ALL
		SELECT 'C' AS [Name] UNION ALL
		SELECT 'Cecylia' AS [Name] UNION ALL
		SELECT 'Celestyna' AS [Name] UNION ALL
		SELECT 'Celina' AS [Name] UNION ALL
		SELECT 'Cezaria' AS [Name] UNION ALL
		SELECT 'Cezaryna' AS [Name] UNION ALL
		SELECT 'Celestia' AS [Name] UNION ALL
		SELECT 'Chociemira' AS [Name] UNION ALL
		SELECT 'Chwalisława' AS [Name] UNION ALL
		SELECT 'Ciechosława' AS [Name] UNION ALL
		SELECT 'Ciesława' AS [Name] UNION ALL
		SELECT 'Cinosława' AS [Name] UNION ALL
		SELECT 'Cina' AS [Name] UNION ALL
		SELECT 'Czesława' AS [Name] UNION ALL
		SELECT 'D' AS [Name] UNION ALL
		SELECT 'Dajmira' AS [Name] UNION ALL
		SELECT 'Dagna' AS [Name] UNION ALL
		SELECT 'Dagmara' AS [Name] UNION ALL
		SELECT 'Dalia' AS [Name] UNION ALL
		SELECT 'Dalila' AS [Name] UNION ALL
		SELECT 'Dalmira' AS [Name] UNION ALL
		SELECT 'Damroka' AS [Name] UNION ALL
		SELECT 'Dana' AS [Name] UNION ALL
		SELECT 'Daniela' AS [Name] UNION ALL
		SELECT 'Danisława' AS [Name] UNION ALL
		SELECT 'Danuta' AS [Name] UNION ALL
		SELECT 'Dargomira' AS [Name] UNION ALL
		SELECT 'Dargosława' AS [Name] UNION ALL
		SELECT 'Daria' AS [Name] UNION ALL
		SELECT 'Dąbrówka' AS [Name] UNION ALL
		SELECT 'Delfina' AS [Name] UNION ALL
		SELECT 'Delia' AS [Name] UNION ALL
		SELECT 'Deresa' AS [Name] UNION ALL
		SELECT 'Desreta' AS [Name] UNION ALL
		SELECT 'Delinda' AS [Name] UNION ALL
		SELECT 'Diana' AS [Name] UNION ALL
		SELECT 'Dilara' AS [Name] UNION ALL
		SELECT 'Dobiesława' AS [Name] UNION ALL
		SELECT 'Dobrochna' AS [Name] UNION ALL
		SELECT 'Domasława' AS [Name] UNION ALL
		SELECT 'Dominika' AS [Name] UNION ALL
		SELECT 'Donata' AS [Name] UNION ALL
		SELECT 'Dorosława' AS [Name] UNION ALL
		SELECT 'Dorota' AS [Name] UNION ALL
		SELECT 'Dymfna' AS [Name] UNION ALL
		SELECT 'Dyzma' AS [Name] UNION ALL
		SELECT 'Dżanan' AS [Name] UNION ALL
		SELECT 'Dżamila' AS [Name] UNION ALL
		SELECT 'Dżesika' AS [Name] UNION ALL
		SELECT 'E' AS [Name] UNION ALL
		SELECT 'Edeltrauda, Edeltruda' AS [Name] UNION ALL
		SELECT 'Edyta' AS [Name] UNION ALL
		SELECT 'Eleonora' AS [Name] UNION ALL
		SELECT 'Eliza' AS [Name] UNION ALL
		SELECT 'Elena' AS [Name] UNION ALL
		SELECT 'Elwira' AS [Name] UNION ALL
		SELECT 'Elżbieta' AS [Name] UNION ALL
		SELECT 'Elmira' AS [Name] UNION ALL
		SELECT 'Elora' AS [Name] UNION ALL
		SELECT 'Emanuela' AS [Name] UNION ALL
		SELECT 'Emilia' AS [Name] UNION ALL
		SELECT 'Emina' AS [Name] UNION ALL
		SELECT 'Emma' AS [Name] UNION ALL
		SELECT 'Ernesta' AS [Name] UNION ALL
		SELECT 'Ernestyna' AS [Name] UNION ALL
		SELECT 'Eryka' AS [Name] UNION ALL
		SELECT 'Estera' AS [Name] UNION ALL
		SELECT 'Eugenia' AS [Name] UNION ALL
		SELECT 'Eunika' AS [Name] UNION ALL
		SELECT 'Ewa' AS [Name] UNION ALL
		SELECT 'Ewarysta' AS [Name] UNION ALL
		SELECT 'Ewelina' AS [Name] UNION ALL
		SELECT 'F' AS [Name] UNION ALL
		SELECT 'Fabia' AS [Name] UNION ALL
		SELECT 'Faria' AS [Name] UNION ALL
		SELECT 'Fabiana' AS [Name] UNION ALL
		SELECT 'Fabiola' AS [Name] UNION ALL
		SELECT 'Farida' AS [Name] UNION ALL
		SELECT 'Fatima' AS [Name] UNION ALL
		SELECT 'Fatma' AS [Name] UNION ALL
		SELECT 'Faustyna' AS [Name] UNION ALL
		SELECT 'Fera' AS [Name] UNION ALL
		SELECT 'Felicja' AS [Name] UNION ALL
		SELECT 'Felicjana' AS [Name] UNION ALL
		SELECT 'Felicyta' AS [Name] UNION ALL
		SELECT 'Feliksa' AS [Name] UNION ALL
		SELECT 'Ferdynanda' AS [Name] UNION ALL
		SELECT 'Filipa' AS [Name] UNION ALL
		SELECT 'Filipina' AS [Name] UNION ALL
		SELECT 'Filomena' AS [Name] UNION ALL
		SELECT 'Flora' AS [Name] UNION ALL
		SELECT 'Florentyna' AS [Name] UNION ALL
		SELECT 'Floriana' AS [Name] UNION ALL
		SELECT 'Franciszka' AS [Name] UNION ALL
		SELECT 'Fryderyka' AS [Name] UNION ALL
		SELECT 'G' AS [Name] UNION ALL
		SELECT 'Gabriela' AS [Name] UNION ALL
		SELECT 'Gaja' AS [Name] UNION ALL
		SELECT 'Genowefa' AS [Name] UNION ALL
		SELECT 'Gerarda' AS [Name] UNION ALL
		SELECT 'Gertruda' AS [Name] UNION ALL
		SELECT 'Gizela' AS [Name] UNION ALL
		SELECT 'Gloria' AS [Name] UNION ALL
		SELECT 'Gniewomira' AS [Name] UNION ALL
		SELECT 'Gracja' AS [Name] UNION ALL
		SELECT 'Gracjana' AS [Name] UNION ALL
		SELECT 'Grażyna' AS [Name] UNION ALL
		SELECT 'Greta' AS [Name] UNION ALL
		SELECT 'Gryzelda' AS [Name] UNION ALL
		SELECT 'Grzymisława' AS [Name] UNION ALL
		SELECT 'Grzymsława' AS [Name] UNION ALL
		SELECT 'Gustawa' AS [Name] UNION ALL
		SELECT 'Gwidona' AS [Name] UNION ALL
		SELECT 'H' AS [Name] UNION ALL
		SELECT 'Hadriana' AS [Name] UNION ALL
		SELECT 'Halina' AS [Name] UNION ALL
		SELECT 'Halszka' AS [Name] UNION ALL
		SELECT 'Hanna' AS [Name] UNION ALL
		SELECT 'Helena' AS [Name] UNION ALL
		SELECT 'Helga' AS [Name] UNION ALL
		SELECT 'Henrieta' AS [Name] UNION ALL
		SELECT 'Henryka' AS [Name] UNION ALL
		SELECT 'Herma' AS [Name] UNION ALL
		SELECT 'Hermana' AS [Name] UNION ALL
		SELECT 'Hermenegilda' AS [Name] UNION ALL
		SELECT 'Hermina' AS [Name] UNION ALL
		SELECT 'Hestia' AS [Name] UNION ALL
		SELECT 'Hiacynta' AS [Name] UNION ALL
		SELECT 'Hilaria' AS [Name] UNION ALL
		SELECT 'Hildegarda' AS [Name] UNION ALL
		SELECT 'Hipolita' AS [Name] UNION ALL
		SELECT 'Honorata' AS [Name] UNION ALL
		SELECT 'Hortensja' AS [Name] UNION ALL
		SELECT 'Huberta' AS [Name] UNION ALL
		SELECT 'I' AS [Name] UNION ALL
		SELECT 'Ida' AS [Name] UNION ALL
		SELECT 'Idosława' AS [Name] UNION ALL
		SELECT 'Idzia' AS [Name] UNION ALL
		SELECT 'Idalia' AS [Name] UNION ALL
		SELECT 'Idzisława' AS [Name] UNION ALL
		SELECT 'Iga' AS [Name] UNION ALL
		SELECT 'Ildefonsa' AS [Name] UNION ALL
		SELECT 'Ilga' AS [Name] UNION ALL
		SELECT 'Ilia' AS [Name] UNION ALL
		SELECT 'Iliana' AS [Name] UNION ALL
		SELECT 'Ilona' AS [Name] UNION ALL
		SELECT 'Ilza' AS [Name] UNION ALL
		SELECT 'Inga' AS [Name] UNION ALL
		SELECT 'Inka' AS [Name] UNION ALL
		SELECT 'Ingeborga' AS [Name] UNION ALL
		SELECT 'Ingryda' AS [Name] UNION ALL
		SELECT 'Irena' AS [Name] UNION ALL
		SELECT 'Iryda' AS [Name] UNION ALL
		SELECT 'Irina' AS [Name] UNION ALL
		SELECT 'Ira' AS [Name] UNION ALL
		SELECT 'Irma' AS [Name] UNION ALL
		SELECT 'Irmina' AS [Name] UNION ALL
		SELECT 'Iwa' AS [Name] UNION ALL
		SELECT 'Iwona' AS [Name] UNION ALL
		SELECT 'Izabela' AS [Name] UNION ALL
		SELECT 'Izolda' AS [Name] UNION ALL
		SELECT 'Izydora' AS [Name] UNION ALL
		SELECT 'J' AS [Name] UNION ALL
		SELECT 'Jadwiga' AS [Name] UNION ALL
		SELECT 'Jagoda' AS [Name] UNION ALL
		SELECT 'Jagna' AS [Name] UNION ALL
		SELECT 'Jana' AS [Name] UNION ALL
		SELECT 'Janina' AS [Name] UNION ALL
		SELECT 'Jarmiła' AS [Name] UNION ALL
		SELECT 'Jaromiła' AS [Name] UNION ALL
		SELECT 'Jaromira' AS [Name] UNION ALL
		SELECT 'Jarosława' AS [Name] UNION ALL
		SELECT 'Jasława' AS [Name] UNION ALL
		SELECT 'Jaśmina' AS [Name] UNION ALL
		SELECT 'Joachima' AS [Name] UNION ALL
		SELECT 'Joanna' AS [Name] UNION ALL
		SELECT 'Jolanta' AS [Name] UNION ALL
		SELECT 'Jowita' AS [Name] UNION ALL
		SELECT 'Józefa' AS [Name] UNION ALL
		SELECT 'Józefina' AS [Name] UNION ALL
		SELECT 'Judyta' AS [Name] UNION ALL
		SELECT 'Julia' AS [Name] UNION ALL
		SELECT 'Julianna' AS [Name] UNION ALL
		SELECT 'Julisława' AS [Name] UNION ALL
		SELECT 'Julita' AS [Name] UNION ALL
		SELECT 'Justyna' AS [Name] UNION ALL
		SELECT 'Juta' AS [Name] UNION ALL
		SELECT 'K' AS [Name] UNION ALL
		SELECT 'Kaja' AS [Name] UNION ALL
		SELECT 'Kama' AS [Name] UNION ALL
		SELECT 'Kalina' AS [Name] UNION ALL
		SELECT 'Kamila' AS [Name] UNION ALL
		SELECT 'Kamira' AS [Name] UNION ALL
		SELECT 'Karima' AS [Name] UNION ALL
		SELECT 'Karina' AS [Name] UNION ALL
		SELECT 'Karola' AS [Name] UNION ALL
		SELECT 'Karolina' AS [Name] UNION ALL
		SELECT 'Karyna' AS [Name] UNION ALL
		SELECT 'Katarzyna' AS [Name] UNION ALL
		SELECT 'Kasandra' AS [Name] UNION ALL
		SELECT 'Kazimiera' AS [Name] UNION ALL
		SELECT 'Kiara' AS [Name] UNION ALL
		SELECT 'Kiliana' AS [Name] UNION ALL
		SELECT 'Kinga' AS [Name] UNION ALL
		SELECT 'Kira' AS [Name] UNION ALL
		SELECT 'Keira' AS [Name] UNION ALL
		SELECT 'Keiria' AS [Name] UNION ALL
		SELECT 'Klara' AS [Name] UNION ALL
		SELECT 'Klarysa' AS [Name] UNION ALL
		SELECT 'Klaudia' AS [Name] UNION ALL
		SELECT 'Klaudyna' AS [Name] UNION ALL
		SELECT 'Klementyna' AS [Name] UNION ALL
		SELECT 'Kleopatra' AS [Name] UNION ALL
		SELECT 'Klotylda' AS [Name] UNION ALL
		SELECT 'Konstancja' AS [Name] UNION ALL
		SELECT 'Kordula' AS [Name] UNION ALL
		SELECT 'Kornelia' AS [Name] UNION ALL
		SELECT 'Koryna' AS [Name] UNION ALL
		SELECT 'Krystiana' AS [Name] UNION ALL
		SELECT 'Krystyna' AS [Name] UNION ALL
		SELECT 'Krzysztofa' AS [Name] UNION ALL
		SELECT 'Ksawera' AS [Name] UNION ALL
		SELECT 'Ksenia' AS [Name] UNION ALL
		SELECT 'Kunegunda' AS [Name] UNION ALL
		SELECT 'Kwiatosława' AS [Name] UNION ALL
		SELECT 'Kwietosława' AS [Name] UNION ALL
		SELECT 'L' AS [Name] UNION ALL
		SELECT 'Laila' AS [Name] UNION ALL
		SELECT 'Lajla' AS [Name] UNION ALL
		SELECT 'Lana' AS [Name] UNION ALL
		SELECT 'Lara' AS [Name] UNION ALL
		SELECT 'Larisa' AS [Name] UNION ALL
		SELECT 'Larysa' AS [Name] UNION ALL
		SELECT 'Latifa' AS [Name] UNION ALL
		SELECT 'Laura' AS [Name] UNION ALL
		SELECT 'Laurencja' AS [Name] UNION ALL
		SELECT 'Lea' AS [Name] UNION ALL
		SELECT 'Leka' AS [Name] UNION ALL
		SELECT 'Lejla' AS [Name] UNION ALL
		SELECT 'Lena' AS [Name] UNION ALL
		SELECT 'Leokadia' AS [Name] UNION ALL
		SELECT 'Leona' AS [Name] UNION ALL
		SELECT 'Leonarda' AS [Name] UNION ALL
		SELECT 'Leoncja' AS [Name] UNION ALL
		SELECT 'Leonora' AS [Name] UNION ALL
		SELECT 'Leontyna' AS [Name] UNION ALL
		SELECT 'Leopolda' AS [Name] UNION ALL
		SELECT 'Letycja' AS [Name] UNION ALL
		SELECT 'Lidia' AS [Name] UNION ALL
		SELECT 'Lila' AS [Name] UNION ALL
		SELECT 'Lisa' AS [Name] UNION ALL
		SELECT 'Ligia' AS [Name] UNION ALL
		SELECT 'Lilia' AS [Name] UNION ALL
		SELECT 'Liliana' AS [Name] UNION ALL
		SELECT 'Lilianna' AS [Name] UNION ALL
		SELECT 'Linda' AS [Name] UNION ALL
		SELECT 'Liwia' AS [Name] UNION ALL
		SELECT 'Lora' AS [Name] UNION ALL
		SELECT 'Luborada' AS [Name] UNION ALL
		SELECT 'Lucjana' AS [Name] UNION ALL
		SELECT 'Lucjola' AS [Name] UNION ALL
		SELECT 'Lucyna' AS [Name] UNION ALL
		SELECT 'Ludmiła' AS [Name] UNION ALL
		SELECT 'Ludolfa' AS [Name] UNION ALL
		SELECT 'Ludwika' AS [Name] UNION ALL
		SELECT 'Ludwina' AS [Name] UNION ALL
		SELECT 'Luiza' AS [Name] UNION ALL
		SELECT 'Luna' AS [Name] UNION ALL
		SELECT 'Lilianna' AS [Name] UNION ALL
		SELECT 'Ł' AS [Name] UNION ALL
		SELECT 'Ładana' AS [Name] UNION ALL
		SELECT 'Ładysława' AS [Name] UNION ALL
		SELECT 'Łagoda' AS [Name] UNION ALL
		SELECT 'Łucja' AS [Name] UNION ALL
		SELECT 'M' AS [Name] UNION ALL
		SELECT 'Macieja' AS [Name] UNION ALL
		SELECT 'Magda' AS [Name] UNION ALL
		SELECT 'Magdalena' AS [Name] UNION ALL
		SELECT 'Maja' AS [Name] UNION ALL
		SELECT 'Maksa' AS [Name] UNION ALL
		SELECT 'Maksyma' AS [Name] UNION ALL
		SELECT 'Malina' AS [Name] UNION ALL
		SELECT 'Malwina' AS [Name] UNION ALL
		SELECT 'Małgorzata' AS [Name] UNION ALL
		SELECT 'Manuela' AS [Name] UNION ALL
		SELECT 'Marcela' AS [Name] UNION ALL
		SELECT 'Marcelina' AS [Name] UNION ALL
		SELECT 'Marcjana' AS [Name] UNION ALL
		SELECT 'Marcjanna' AS [Name] UNION ALL
		SELECT 'Maria' AS [Name] UNION ALL
		SELECT 'Mariam' AS [Name] UNION ALL
		SELECT 'Marianna' AS [Name] UNION ALL
		SELECT 'Marietta' AS [Name] UNION ALL
		SELECT 'Marika' AS [Name] UNION ALL
		SELECT 'Mariola' AS [Name] UNION ALL
		SELECT 'Marlena' AS [Name] UNION ALL
		SELECT 'Marta' AS [Name] UNION ALL
		SELECT 'Martyna' AS [Name] UNION ALL
		SELECT 'Maryja' AS [Name] UNION ALL
		SELECT 'Maryla' AS [Name] UNION ALL
		SELECT 'Maryna' AS [Name] UNION ALL
		SELECT 'Marzena' AS [Name] UNION ALL
		SELECT 'Matylda' AS [Name] UNION ALL
		SELECT 'Melania' AS [Name] UNION ALL
		SELECT 'Michalina' AS [Name] UNION ALL
		SELECT 'Mieczysława' AS [Name] UNION ALL
		SELECT 'Milena' AS [Name] UNION ALL
		SELECT 'Milomira' AS [Name] UNION ALL
		SELECT 'Miłosława' AS [Name] UNION ALL
		SELECT 'Miłowita' AS [Name] UNION ALL
		SELECT 'Minerwa' AS [Name] UNION ALL
		SELECT 'Mina' AS [Name] UNION ALL
		SELECT 'Mira' AS [Name] UNION ALL
		SELECT 'Mirabela' AS [Name] UNION ALL
		SELECT 'Miranda' AS [Name] UNION ALL
		SELECT 'Mirela' AS [Name] UNION ALL
		SELECT 'Miriam' AS [Name] UNION ALL
		SELECT 'Mirka' AS [Name] UNION ALL
		SELECT 'Miroda' AS [Name] UNION ALL
		SELECT 'Mirołada' AS [Name] UNION ALL
		SELECT 'Mirosława' AS [Name] UNION ALL
		SELECT 'Mojmira' AS [Name] UNION ALL
		SELECT 'Mojra' AS [Name] UNION ALL
		SELECT 'Monika' AS [Name] UNION ALL
		SELECT 'Morzana' AS [Name] UNION ALL
		SELECT 'Morzena' AS [Name] UNION ALL
		SELECT 'N' AS [Name] UNION ALL
		SELECT 'Nadia' AS [Name] UNION ALL
		SELECT 'Nadzieja' AS [Name] UNION ALL
		SELECT 'Najmiła' AS [Name] UNION ALL
		SELECT 'Najsława' AS [Name] UNION ALL
		SELECT 'Narcyza' AS [Name] UNION ALL
		SELECT 'Natalia' AS [Name] UNION ALL
		SELECT 'Natasza' AS [Name] UNION ALL
		SELECT 'Nela' AS [Name] UNION ALL
		SELECT 'Nika' AS [Name] UNION ALL
		SELECT 'Nikodema' AS [Name] UNION ALL
		SELECT 'Nikola' AS [Name] UNION ALL
		SELECT 'Nitara' AS [Name] UNION ALL
		SELECT 'Nikoleta' AS [Name] UNION ALL
		SELECT 'Nina' AS [Name] UNION ALL
		SELECT 'Nira' AS [Name] UNION ALL
		SELECT 'Noemi' AS [Name] UNION ALL
		SELECT 'Nora' AS [Name] UNION ALL
		SELECT 'Norberta' AS [Name] UNION ALL
		SELECT 'Norma' AS [Name] UNION ALL
		SELECT 'O' AS [Name] UNION ALL
		SELECT 'Oda' AS [Name] UNION ALL
		SELECT 'Odeta' AS [Name] UNION ALL
		SELECT 'Odyla' AS [Name] UNION ALL
		SELECT 'Ofelia' AS [Name] UNION ALL
		SELECT 'Oksana' AS [Name] UNION ALL
		SELECT 'Oktawia' AS [Name] UNION ALL
		SELECT 'Olga' AS [Name] UNION ALL
		SELECT 'Olimpia' AS [Name] UNION ALL
		SELECT 'Oliwia' AS [Name] UNION ALL
		SELECT 'Oriana' AS [Name] UNION ALL
		SELECT 'Ota' AS [Name] UNION ALL
		SELECT 'Otylia' AS [Name] UNION ALL
		SELECT 'Ożanna' AS [Name] UNION ALL
		SELECT 'Obina' AS [Name] UNION ALL
		SELECT 'Olena' AS [Name] UNION ALL
		SELECT 'P' AS [Name] UNION ALL
		SELECT 'Pabiana' AS [Name] UNION ALL
		SELECT 'Pamela' AS [Name] UNION ALL
		SELECT 'Patrycja' AS [Name] UNION ALL
		SELECT 'Paula' AS [Name] UNION ALL
		SELECT 'Paulina' AS [Name] UNION ALL
		SELECT 'Pelagia' AS [Name] UNION ALL
		SELECT 'Petra' AS [Name] UNION ALL
		SELECT 'Petronela' AS [Name] UNION ALL
		SELECT 'Petronia' AS [Name] UNION ALL
		SELECT 'Placyda' AS [Name] UNION ALL
		SELECT 'Pola' AS [Name] UNION ALL
		SELECT 'Polianna' AS [Name] UNION ALL
		SELECT 'Polmira' AS [Name] UNION ALL
		SELECT 'Przemysława' AS [Name] UNION ALL
		SELECT 'Przybysława' AS [Name] UNION ALL
		SELECT 'R' AS [Name] UNION ALL
		SELECT 'Rachela' AS [Name] UNION ALL
		SELECT 'Ramona' AS [Name] UNION ALL
		SELECT 'Radmiła' AS [Name] UNION ALL
		SELECT 'Radomiła' AS [Name] UNION ALL
		SELECT 'Radomira' AS [Name] UNION ALL
		SELECT 'Radosława' AS [Name] UNION ALL
		SELECT 'Rafaela' AS [Name] UNION ALL
		SELECT 'Rajmunda' AS [Name] UNION ALL
		SELECT 'Rajna' AS [Name] UNION ALL
		SELECT 'Raszyda' AS [Name] UNION ALL
		SELECT 'Rebeka' AS [Name] UNION ALL
		SELECT 'Regina' AS [Name] UNION ALL
		SELECT 'Remigia' AS [Name] UNION ALL
		SELECT 'Renata' AS [Name] UNION ALL
		SELECT 'Rejna' AS [Name] UNION ALL
		SELECT 'Rita' AS [Name] UNION ALL
		SELECT 'Roberta' AS [Name] UNION ALL
		SELECT 'Rodzisława' AS [Name] UNION ALL
		SELECT 'Roksana' AS [Name] UNION ALL
		SELECT 'Roma' AS [Name] UNION ALL
		SELECT 'Romana' AS [Name] UNION ALL
		SELECT 'Romualda' AS [Name] UNION ALL
		SELECT 'Rozalia' AS [Name] UNION ALL
		SELECT 'Rozalinda' AS [Name] UNION ALL
		SELECT 'Rozamunda' AS [Name] UNION ALL
		SELECT 'Rozetta' AS [Name] UNION ALL
		SELECT 'Rozwita' AS [Name] UNION ALL
		SELECT 'Róża' AS [Name] UNION ALL
		SELECT 'Rudolfina' AS [Name] UNION ALL
		SELECT 'Rut' AS [Name] UNION ALL
		SELECT 'Ruta' AS [Name] UNION ALL
		SELECT 'Ryksa' AS [Name] UNION ALL
		SELECT 'Ryta' AS [Name] UNION ALL
		SELECT 'Ryszarda' AS [Name] UNION ALL
		SELECT 'S' AS [Name] UNION ALL
		SELECT 'Sabina' AS [Name] UNION ALL
		SELECT 'Sabrina' AS [Name] UNION ALL
		SELECT 'Sarina' AS [Name] UNION ALL
		SELECT 'Sarita' AS [Name] UNION ALL
		SELECT 'Safira' AS [Name] UNION ALL
		SELECT 'Safana' AS [Name] UNION ALL
		SELECT 'Salma' AS [Name] UNION ALL
		SELECT 'Saloma' AS [Name] UNION ALL
		SELECT 'Salomea' AS [Name] UNION ALL
		SELECT 'Samanta' AS [Name] UNION ALL
		SELECT 'Samantra' AS [Name] UNION ALL
		SELECT 'Samara' AS [Name] UNION ALL
		SELECT 'Sandra' AS [Name] UNION ALL
		SELECT 'Sara' AS [Name] UNION ALL
		SELECT 'Semira' AS [Name] UNION ALL
		SELECT 'Sebastiana' AS [Name] UNION ALL
		SELECT 'Selena' AS [Name] UNION ALL
		SELECT 'Selma' AS [Name] UNION ALL
		SELECT 'Serafina' AS [Name] UNION ALL
		SELECT 'Seweryna' AS [Name] UNION ALL
		SELECT 'Sędomira' AS [Name] UNION ALL
		SELECT 'Sędzisława' AS [Name] UNION ALL
		SELECT 'Sława' AS [Name] UNION ALL
		SELECT 'Sławina' AS [Name] UNION ALL
		SELECT 'Sławomira' AS [Name] UNION ALL
		SELECT 'Sobiesława' AS [Name] UNION ALL
		SELECT 'Sonia' AS [Name] UNION ALL
		SELECT 'Stamira' AS [Name] UNION ALL
		SELECT 'Stanisława' AS [Name] UNION ALL
		SELECT 'Stefania' AS [Name] UNION ALL
		SELECT 'Stela' AS [Name] UNION ALL
		SELECT 'Stoisława' AS [Name] UNION ALL
		SELECT 'Stella' AS [Name] UNION ALL
		SELECT 'Strzeżymira' AS [Name] UNION ALL
		SELECT 'Subisława' AS [Name] UNION ALL
		SELECT 'Sulima' AS [Name] UNION ALL
		SELECT 'Sulisława' AS [Name] UNION ALL
		SELECT 'Sybilla' AS [Name] UNION ALL
		SELECT 'Sydonia' AS [Name] UNION ALL
		SELECT 'Sylwana' AS [Name] UNION ALL
		SELECT 'Sylwia' AS [Name] UNION ALL
		SELECT 'Szarlota' AS [Name] UNION ALL
		SELECT 'Szarlin' AS [Name] UNION ALL
		SELECT 'Szarlina' AS [Name] UNION ALL
		SELECT 'Szejma' AS [Name] UNION ALL
		SELECT 'Szymona' AS [Name] UNION ALL
		SELECT 'Ś' AS [Name] UNION ALL
		SELECT 'Świetlana' AS [Name] UNION ALL
		SELECT 'Świętomira' AS [Name] UNION ALL
		SELECT 'Świętosława' AS [Name] UNION ALL
		SELECT 'T' AS [Name] UNION ALL
		SELECT 'Tabita' AS [Name] UNION ALL
		SELECT 'Tacjana' AS [Name] UNION ALL
		SELECT 'Tadea' AS [Name] UNION ALL
		SELECT 'Tamara' AS [Name] UNION ALL
		SELECT 'Tatiana' AS [Name] UNION ALL
		SELECT 'Tekla' AS [Name] UNION ALL
		SELECT 'Telimena' AS [Name] UNION ALL
		SELECT 'Teodora' AS [Name] UNION ALL
		SELECT 'Teodozja' AS [Name] UNION ALL
		SELECT 'Teofila' AS [Name] UNION ALL
		SELECT 'Teresa' AS [Name] UNION ALL
		SELECT 'Tęgomira' AS [Name] UNION ALL
		SELECT 'Tina' AS [Name] UNION ALL
		SELECT 'Tolisława' AS [Name] UNION ALL
		SELECT 'Tomiła' AS [Name] UNION ALL
		SELECT 'Tomisława' AS [Name] UNION ALL
		SELECT 'Tulimira' AS [Name] UNION ALL
		SELECT 'Tessa' AS [Name] UNION ALL
		SELECT 'Tymora' AS [Name] UNION ALL
		SELECT 'Tyria' AS [Name] UNION ALL
		SELECT 'Tybita' AS [Name] UNION ALL
		SELECT 'Tybilla' AS [Name] UNION ALL
		SELECT 'U' AS [Name] UNION ALL
		SELECT 'Ulana' AS [Name] UNION ALL
		SELECT 'Ulryka' AS [Name] UNION ALL
		SELECT 'Unima' AS [Name] UNION ALL
		SELECT 'Urszula' AS [Name] UNION ALL
		SELECT 'Uta' AS [Name] UNION ALL
		SELECT 'W' AS [Name] UNION ALL
		SELECT 'Wacława' AS [Name] UNION ALL
		SELECT 'Walentyna' AS [Name] UNION ALL
		SELECT 'Waleria' AS [Name] UNION ALL
		SELECT 'Wanda' AS [Name] UNION ALL
		SELECT 'Wanessa' AS [Name] UNION ALL
		SELECT 'Weronika' AS [Name] UNION ALL
		SELECT 'Weridiana' AS [Name] UNION ALL
		SELECT 'Wiara' AS [Name] UNION ALL
		SELECT 'Wiesława' AS [Name] UNION ALL
		SELECT 'Wierzchosława' AS [Name] UNION ALL
		SELECT 'Wiktoria' AS [Name] UNION ALL
		SELECT 'Wiktoryna' AS [Name] UNION ALL
		SELECT 'Wilhelmina' AS [Name] UNION ALL
		SELECT 'Wincentyna' AS [Name] UNION ALL
		SELECT 'Wioleta' AS [Name] UNION ALL
		SELECT 'Wioletta' AS [Name] UNION ALL
		SELECT 'Wirgilia' AS [Name] UNION ALL
		SELECT 'Wirginia' AS [Name] UNION ALL
		SELECT 'Wisława' AS [Name] UNION ALL
		SELECT 'Witosława' AS [Name] UNION ALL
		SELECT 'Władysława' AS [Name] UNION ALL
		SELECT 'Włodzimiera' AS [Name] UNION ALL
		SELECT 'Wolimira' AS [Name] UNION ALL
		SELECT 'Wrocisława' AS [Name] UNION ALL
		SELECT 'Z' AS [Name] UNION ALL
		SELECT 'Zaida' AS [Name] UNION ALL
		SELECT 'Zaira' AS [Name] UNION ALL
		SELECT 'Zdzisława' AS [Name] UNION ALL
		SELECT 'Zefiryna' AS [Name] UNION ALL
		SELECT 'Zenobia' AS [Name] UNION ALL
		SELECT 'Zenona' AS [Name] UNION ALL
		SELECT 'Zofia' AS [Name] UNION ALL
		SELECT 'Zoja' AS [Name] UNION ALL
		SELECT 'Zuzanna' AS [Name] UNION ALL
		SELECT 'Zwinisława' AS [Name] UNION ALL
		SELECT 'Zygfryda' AS [Name] UNION ALL
		SELECT 'Zygmunta' AS [Name] UNION ALL
		SELECT 'Zyta' AS [Name] UNION ALL
		SELECT 'Ż' AS [Name] UNION ALL
		SELECT 'Żaklina' AS [Name] UNION ALL
		SELECT 'Żaneta' AS [Name] UNION ALL
		SELECT 'Żanna' AS [Name] UNION ALL
		SELECT 'Żelisława' AS [Name] UNION ALL
		SELECT 'Żużanna' AS [Name] UNION ALL
		SELECT 'Żywia' AS [Name] UNION ALL
		SELECT 'Żywisława' AS [Name] UNION ALL
		SELECT 'Imiona męskie' AS [Name] UNION ALL
		SELECT 'A' AS [Name] UNION ALL
		SELECT 'Aaron' AS [Name] UNION ALL
		SELECT 'Abdon' AS [Name] UNION ALL
		SELECT 'Abel' AS [Name] UNION ALL
		SELECT 'Abelard' AS [Name] UNION ALL
		SELECT 'Abraham' AS [Name] UNION ALL
		SELECT 'Achilles' AS [Name] UNION ALL
		SELECT 'Adam' AS [Name] UNION ALL
		SELECT 'Adelard' AS [Name] UNION ALL
		SELECT 'Adnan' AS [Name] UNION ALL
		SELECT 'Adrian' AS [Name] UNION ALL
		SELECT 'Agapit' AS [Name] UNION ALL
		SELECT 'Agaton' AS [Name] UNION ALL
		SELECT 'Agrypin' AS [Name] UNION ALL
		SELECT 'Ajdin' AS [Name] UNION ALL
		SELECT 'Albert' AS [Name] UNION ALL
		SELECT 'Alan' AS [Name] UNION ALL
		SELECT 'Albin' AS [Name] UNION ALL
		SELECT 'Albrecht' AS [Name] UNION ALL
		SELECT 'Aleks' AS [Name] UNION ALL
		SELECT 'Aleksander' AS [Name] UNION ALL
		SELECT 'Aleksy' AS [Name] UNION ALL
		SELECT 'Alfons' AS [Name] UNION ALL
		SELECT 'Alfred' AS [Name] UNION ALL
		SELECT 'Alojzy' AS [Name] UNION ALL
		SELECT 'Alwin' AS [Name] UNION ALL
		SELECT 'Amadeusz' AS [Name] UNION ALL
		SELECT 'Ambroży' AS [Name] UNION ALL
		SELECT 'Anastazy' AS [Name] UNION ALL
		SELECT 'Ananiasz' AS [Name] UNION ALL
		SELECT 'Anatol' AS [Name] UNION ALL
		SELECT 'Andrzej' AS [Name] UNION ALL
		SELECT 'Anioł' AS [Name] UNION ALL
		SELECT 'Annasz' AS [Name] UNION ALL
		SELECT 'Antoni' AS [Name] UNION ALL
		SELECT 'Antonin' AS [Name] UNION ALL
		SELECT 'Antonius' AS [Name] UNION ALL
		SELECT 'Anzelm' AS [Name] UNION ALL
		SELECT 'Apolinary' AS [Name] UNION ALL
		SELECT 'Apollo' AS [Name] UNION ALL
		SELECT 'Apoloniusz' AS [Name] UNION ALL
		SELECT 'Ariel' AS [Name] UNION ALL
		SELECT 'Arkadiusz' AS [Name] UNION ALL
		SELECT 'Arkady' AS [Name] UNION ALL
		SELECT 'Arnold' AS [Name] UNION ALL
		SELECT 'Artur' AS [Name] UNION ALL
		SELECT 'August' AS [Name] UNION ALL
		SELECT 'Augustyn' AS [Name] UNION ALL
		SELECT 'Aurelian' AS [Name] UNION ALL
		SELECT 'B' AS [Name] UNION ALL
		SELECT 'Baldwin' AS [Name] UNION ALL
		SELECT 'Baltazar' AS [Name] UNION ALL
		SELECT 'Barabasz' AS [Name] UNION ALL
		SELECT 'Barnaba' AS [Name] UNION ALL
		SELECT 'Barnim' AS [Name] UNION ALL
		SELECT 'Bartłomiej' AS [Name] UNION ALL
		SELECT 'Bartosz' AS [Name] UNION ALL
		SELECT 'Bazyli' AS [Name] UNION ALL
		SELECT 'Beat' AS [Name] UNION ALL
		SELECT 'Benedykt' AS [Name] UNION ALL
		SELECT 'Beniamin' AS [Name] UNION ALL
		SELECT 'Benon' AS [Name] UNION ALL
		SELECT 'Bernard' AS [Name] UNION ALL
		SELECT 'Bert' AS [Name] UNION ALL
		SELECT 'Błażej' AS [Name] UNION ALL
		SELECT 'Bodosław' AS [Name] UNION ALL
		SELECT 'Bogdał' AS [Name] UNION ALL
		SELECT 'Bogdan' AS [Name] UNION ALL
		SELECT 'Boguchwał' AS [Name] UNION ALL
		SELECT 'Bogumił' AS [Name] UNION ALL
		SELECT 'Bogumir' AS [Name] UNION ALL
		SELECT 'Bogusław' AS [Name] UNION ALL
		SELECT 'Bogusz' AS [Name] UNION ALL
		SELECT 'Bolebor' AS [Name] UNION ALL
		SELECT 'Bolelut' AS [Name] UNION ALL
		SELECT 'Bolesław' AS [Name] UNION ALL
		SELECT 'Bonawentura' AS [Name] UNION ALL
		SELECT 'Bonifacy' AS [Name] UNION ALL
		SELECT 'Borys' AS [Name] UNION ALL
		SELECT 'Borysław' AS [Name] UNION ALL
		SELECT 'Borzywoj' AS [Name] UNION ALL
		SELECT 'Bożan' AS [Name] UNION ALL
		SELECT 'Bożidar' AS [Name] UNION ALL
		SELECT 'Bożydar' AS [Name] UNION ALL
		SELECT 'Bożimir' AS [Name] UNION ALL
		SELECT 'Bromir' AS [Name] UNION ALL
		SELECT 'Bronisław' AS [Name] UNION ALL
		SELECT 'Bruno' AS [Name] UNION ALL
		SELECT 'Brunon' AS [Name] UNION ALL
		SELECT 'Budzisław' AS [Name] UNION ALL
		SELECT 'C' AS [Name] UNION ALL
		SELECT 'Cecyl' AS [Name] UNION ALL
		SELECT 'Cecylian' AS [Name] UNION ALL
		SELECT 'Celestyn' AS [Name] UNION ALL
		SELECT 'Cezar' AS [Name] UNION ALL
		SELECT 'Cezary' AS [Name] UNION ALL
		SELECT 'Chociemir' AS [Name] UNION ALL
		SELECT 'Chrystian' AS [Name] UNION ALL
		SELECT 'Chwalibóg' AS [Name] UNION ALL
		SELECT 'Chwalimir' AS [Name] UNION ALL
		SELECT 'Chwalisław' AS [Name] UNION ALL
		SELECT 'Cichosław' AS [Name] UNION ALL
		SELECT 'Ciechosław' AS [Name] UNION ALL
		SELECT 'Cyprian' AS [Name] UNION ALL
		SELECT 'Cyryl' AS [Name] UNION ALL
		SELECT 'Czesław' AS [Name] UNION ALL
		SELECT 'D' AS [Name] UNION ALL
		SELECT 'Dacjusz' AS [Name] UNION ALL
		SELECT 'Dajmir' AS [Name] UNION ALL
		SELECT 'Dal' AS [Name] UNION ALL
		SELECT 'Dalbor' AS [Name] UNION ALL
		SELECT 'Dalgur' AS [Name] UNION ALL
		SELECT 'Damazy' AS [Name] UNION ALL
		SELECT 'Damian' AS [Name] UNION ALL
		SELECT 'Daniel' AS [Name] UNION ALL
		SELECT 'Danisław' AS [Name] UNION ALL
		SELECT 'Danko' AS [Name] UNION ALL
		SELECT 'Dargomir' AS [Name] UNION ALL
		SELECT 'Dargosław' AS [Name] UNION ALL
		SELECT 'Dariusz' AS [Name] UNION ALL
		SELECT 'Darwit' AS [Name] UNION ALL
		SELECT 'Dawid' AS [Name] UNION ALL
		SELECT 'Denis' AS [Name] UNION ALL
		SELECT 'Derwit' AS [Name] UNION ALL
		SELECT 'Dionizy' AS [Name] UNION ALL
		SELECT 'Dobiesław' AS [Name] UNION ALL
		SELECT 'Dobrogost' AS [Name] UNION ALL
		SELECT 'Dobrosław' AS [Name] UNION ALL
		SELECT 'Domasław' AS [Name] UNION ALL
		SELECT 'Dominik' AS [Name] UNION ALL
		SELECT 'Donald' AS [Name] UNION ALL
		SELECT 'Donat' AS [Name] UNION ALL
		SELECT 'Dorian' AS [Name] UNION ALL
		SELECT 'Duszan' AS [Name] UNION ALL
		SELECT 'Dymitr' AS [Name] UNION ALL
		SELECT 'Dyter' AS [Name] UNION ALL
		SELECT 'Dzwonimierz' AS [Name] UNION ALL
		SELECT 'Dżamil' AS [Name] UNION ALL
		SELECT 'Dżan' AS [Name] UNION ALL
		SELECT 'Dżem' AS [Name] UNION ALL
		SELECT 'Dżemil' AS [Name] UNION ALL
		SELECT 'E' AS [Name] UNION ALL
		SELECT 'Edgar' AS [Name] UNION ALL
		SELECT 'Edmund' AS [Name] UNION ALL
		SELECT 'Edward' AS [Name] UNION ALL
		SELECT 'Edwin' AS [Name] UNION ALL
		SELECT 'Efraim' AS [Name] UNION ALL
		SELECT 'Efrem' AS [Name] UNION ALL
		SELECT 'Eliasz' AS [Name] UNION ALL
		SELECT 'Eligiusz' AS [Name] UNION ALL
		SELECT 'Eliot' AS [Name] UNION ALL
		SELECT 'Emanuel' AS [Name] UNION ALL
		SELECT 'Emil' AS [Name] UNION ALL
		SELECT 'Emir' AS [Name] UNION ALL
		SELECT 'Erazm' AS [Name] UNION ALL
		SELECT 'Ernest' AS [Name] UNION ALL
		SELECT 'Erwin' AS [Name] UNION ALL
		SELECT 'Eugeniusz' AS [Name] UNION ALL
		SELECT 'Eryk' AS [Name] UNION ALL
		SELECT 'Ewald' AS [Name] UNION ALL
		SELECT 'Ewaryst' AS [Name] UNION ALL
		SELECT 'Ezaw' AS [Name] UNION ALL
		SELECT 'Ezechiel' AS [Name] UNION ALL
		SELECT 'F' AS [Name] UNION ALL
		SELECT 'Fabian' AS [Name] UNION ALL
		SELECT 'Famian' AS [Name] UNION ALL
		SELECT 'Farid' AS [Name] UNION ALL
		SELECT 'Faris' AS [Name] UNION ALL
		SELECT 'Faustyn' AS [Name] UNION ALL
		SELECT 'Felicjan' AS [Name] UNION ALL
		SELECT 'Feliks' AS [Name] UNION ALL
		SELECT 'Ferdynand' AS [Name] UNION ALL
		SELECT 'Filip' AS [Name] UNION ALL
		SELECT 'Florentyn' AS [Name] UNION ALL
		SELECT 'Florian' AS [Name] UNION ALL
		SELECT 'Fortunat' AS [Name] UNION ALL
		SELECT 'Franciszek' AS [Name] UNION ALL
		SELECT 'Fryc' AS [Name] UNION ALL
		SELECT 'Fryderyk' AS [Name] UNION ALL
		SELECT 'G' AS [Name] UNION ALL
		SELECT 'Gabriel' AS [Name] UNION ALL
		SELECT 'Gaj' AS [Name] UNION ALL
		SELECT 'Gardomir' AS [Name] UNION ALL
		SELECT 'Gaweł' AS [Name] UNION ALL
		SELECT 'Gerard' AS [Name] UNION ALL
		SELECT 'Gerwazy' AS [Name] UNION ALL
		SELECT 'Gilbert' AS [Name] UNION ALL
		SELECT 'Ginter' AS [Name] UNION ALL
		SELECT 'Gniewomir' AS [Name] UNION ALL
		SELECT 'Gniewosz' AS [Name] UNION ALL
		SELECT 'Godehard' AS [Name] UNION ALL
		SELECT 'Godfryg' AS [Name] UNION ALL
		SELECT 'Godfryd' AS [Name] UNION ALL
		SELECT 'Godzisław' AS [Name] UNION ALL
		SELECT 'Gościsław' AS [Name] UNION ALL
		SELECT 'Gotard' AS [Name] UNION ALL
		SELECT 'Gotszalk' AS [Name] UNION ALL
		SELECT 'Gracjan' AS [Name] UNION ALL
		SELECT 'Grodzisław' AS [Name] UNION ALL
		SELECT 'Grzegorz' AS [Name] UNION ALL
		SELECT 'Grzymisław' AS [Name] UNION ALL
		SELECT 'Gualfard' AS [Name] UNION ALL
		SELECT 'Gustaw' AS [Name] UNION ALL
		SELECT 'Gwalbert' AS [Name] UNION ALL
		SELECT 'Gwido' AS [Name] UNION ALL
		SELECT 'Gwidon' AS [Name] UNION ALL
		SELECT 'H' AS [Name] UNION ALL
		SELECT 'Hadrian' AS [Name] UNION ALL
		SELECT 'Hasan' AS [Name] UNION ALL
		SELECT 'Hektor' AS [Name] UNION ALL
		SELECT 'Heliodor' AS [Name] UNION ALL
		SELECT 'Henryk' AS [Name] UNION ALL
		SELECT 'Herakles' AS [Name] UNION ALL
		SELECT 'Herakliusz' AS [Name] UNION ALL
		SELECT 'Herbert' AS [Name] UNION ALL
		SELECT 'Herman' AS [Name] UNION ALL
		SELECT 'Hermes' AS [Name] UNION ALL
		SELECT 'Hiacynt' AS [Name] UNION ALL
		SELECT 'Hieronim' AS [Name] UNION ALL
		SELECT 'Hilary' AS [Name] UNION ALL
		SELECT 'Hipolit' AS [Name] UNION ALL
		SELECT 'Honorat' AS [Name] UNION ALL
		SELECT 'Horacy' AS [Name] UNION ALL
		SELECT 'Hubert' AS [Name] UNION ALL
		SELECT 'Hugo' AS [Name] UNION ALL
		SELECT 'Hugon' AS [Name] UNION ALL
		SELECT 'Husajn' AS [Name] UNION ALL
		SELECT 'I' AS [Name] UNION ALL
		SELECT 'Idzi' AS [Name] UNION ALL
		SELECT 'Ignacy' AS [Name] UNION ALL
		SELECT 'Igor' AS [Name] UNION ALL
		SELECT 'Ildefons' AS [Name] UNION ALL
		SELECT 'Inocenty' AS [Name] UNION ALL
		SELECT 'Ireneusz' AS [Name] UNION ALL
		SELECT 'Iwan' AS [Name] UNION ALL
		SELECT 'Iwo' AS [Name] UNION ALL
		SELECT 'Iwon' AS [Name] UNION ALL
		SELECT 'Izajasz' AS [Name] UNION ALL
		SELECT 'Izydor' AS [Name] UNION ALL
		SELECT 'J' AS [Name] UNION ALL
		SELECT 'Jacek' AS [Name] UNION ALL
		SELECT 'Jacenty' AS [Name] UNION ALL
		SELECT 'Jakub' AS [Name] UNION ALL
		SELECT 'Jan' AS [Name] UNION ALL
		SELECT 'January' AS [Name] UNION ALL
		SELECT 'Janusz' AS [Name] UNION ALL
		SELECT 'Jarad' AS [Name] UNION ALL
		SELECT 'Jaromir' AS [Name] UNION ALL
		SELECT 'Jaropełk' AS [Name] UNION ALL
		SELECT 'Jarosław' AS [Name] UNION ALL
		SELECT 'Jarowit' AS [Name] UNION ALL
		SELECT 'Jeremiasz' AS [Name] UNION ALL
		SELECT 'Jerzy' AS [Name] UNION ALL
		SELECT 'Jędrzej' AS [Name] UNION ALL
		SELECT 'Joachim' AS [Name] UNION ALL
		SELECT 'Jona' AS [Name] UNION ALL
		SELECT 'Jonasz' AS [Name] UNION ALL
		SELECT 'Jonatan' AS [Name] UNION ALL
		SELECT 'Jozafat' AS [Name] UNION ALL
		SELECT 'Józef' AS [Name] UNION ALL
		SELECT 'Józefat' AS [Name] UNION ALL
		SELECT 'Julian' AS [Name] UNION ALL
		SELECT 'Juliusz' AS [Name] UNION ALL
		SELECT 'Jur' AS [Name] UNION ALL
		SELECT 'Juri' AS [Name] UNION ALL
		SELECT 'Justyn' AS [Name] UNION ALL
		SELECT 'Justynian' AS [Name] UNION ALL
		SELECT 'Jasuf' AS [Name] UNION ALL
		SELECT 'K' AS [Name] UNION ALL
		SELECT 'Kacper' AS [Name] UNION ALL
		SELECT 'Kajetan' AS [Name] UNION ALL
		SELECT 'Kajfasz' AS [Name] UNION ALL
		SELECT 'Kajusz' AS [Name] UNION ALL
		SELECT 'Kamil' AS [Name] UNION ALL
		SELECT 'Kanimir' AS [Name] UNION ALL
		SELECT 'Karol' AS [Name] UNION ALL
		SELECT 'Kasjusz' AS [Name] UNION ALL
		SELECT 'Kasper' AS [Name] UNION ALL
		SELECT 'Kastor' AS [Name] UNION ALL
		SELECT 'Kazimierz' AS [Name] UNION ALL
		SELECT 'Kemal' AS [Name] UNION ALL
		SELECT 'Kilian' AS [Name] UNION ALL
		SELECT 'Klaudiusz' AS [Name] UNION ALL
		SELECT 'Klemens' AS [Name] UNION ALL
		SELECT 'Kochan' AS [Name] UNION ALL
		SELECT 'Konrad' AS [Name] UNION ALL
		SELECT 'Konradyn' AS [Name] UNION ALL
		SELECT 'Konstancjusz' AS [Name] UNION ALL
		SELECT 'Konstanty' AS [Name] UNION ALL
		SELECT 'Konstantyn' AS [Name] UNION ALL
		SELECT 'Kordian' AS [Name] UNION ALL
		SELECT 'Kornel' AS [Name] UNION ALL
		SELECT 'Korneli' AS [Name] UNION ALL
		SELECT 'Korneliusz' AS [Name] UNION ALL
		SELECT 'Kosma' AS [Name] UNION ALL
		SELECT 'Kryspin' AS [Name] UNION ALL
		SELECT 'Krystian' AS [Name] UNION ALL
		SELECT 'Krystyn' AS [Name] UNION ALL
		SELECT 'Krzesimir' AS [Name] UNION ALL
		SELECT 'Krzesisław' AS [Name] UNION ALL
		SELECT 'Krzysztof' AS [Name] UNION ALL
		SELECT 'Ksawery' AS [Name] UNION ALL
		SELECT 'Kwiatosław' AS [Name] UNION ALL
		SELECT 'Kwietosław' AS [Name] UNION ALL
		SELECT 'L' AS [Name] UNION ALL
		SELECT 'Lambert' AS [Name] UNION ALL
		SELECT 'Laurencjusz' AS [Name] UNION ALL
		SELECT 'Lech' AS [Name] UNION ALL
		SELECT 'Lechosław' AS [Name] UNION ALL
		SELECT 'Lenart' AS [Name] UNION ALL
		SELECT 'Leo' AS [Name] UNION ALL
		SELECT 'Leon' AS [Name] UNION ALL
		SELECT 'Leokadiusz' AS [Name] UNION ALL
		SELECT 'Leonard' AS [Name] UNION ALL
		SELECT 'Leopold' AS [Name] UNION ALL
		SELECT 'Lesław' AS [Name] UNION ALL
		SELECT 'Leszek' AS [Name] UNION ALL
		SELECT 'Lew' AS [Name] UNION ALL
		SELECT 'Longin' AS [Name] UNION ALL
		SELECT 'Lubisław' AS [Name] UNION ALL
		SELECT 'Lubogost' AS [Name] UNION ALL
		SELECT 'Lubomił' AS [Name] UNION ALL
		SELECT 'Lubomir' AS [Name] UNION ALL
		SELECT 'Luborad' AS [Name] UNION ALL
		SELECT 'Lubosław' AS [Name] UNION ALL
		SELECT 'Lucjan' AS [Name] UNION ALL
		SELECT 'Ludmił' AS [Name] UNION ALL
		SELECT 'Ludomił' AS [Name] UNION ALL
		SELECT 'Ludolf' AS [Name] UNION ALL
		SELECT 'Ludomir' AS [Name] UNION ALL
		SELECT 'Ludowit' AS [Name] UNION ALL
		SELECT 'Ludwik' AS [Name] UNION ALL
		SELECT 'Ł' AS [Name] UNION ALL
		SELECT 'Ładysław' AS [Name] UNION ALL
		SELECT 'Łazarz' AS [Name] UNION ALL
		SELECT 'Łucjan' AS [Name] UNION ALL
		SELECT 'Łukasz' AS [Name] UNION ALL
		SELECT 'M' AS [Name] UNION ALL
		SELECT 'Machut' AS [Name] UNION ALL
		SELECT 'Maciej' AS [Name] UNION ALL
		SELECT 'Magnus' AS [Name] UNION ALL
		SELECT 'Makary' AS [Name] UNION ALL
		SELECT 'Makryn' AS [Name] UNION ALL
		SELECT 'Maksymilian' AS [Name] UNION ALL
		SELECT 'Maksymin' AS [Name] UNION ALL
		SELECT 'Malachiasz' AS [Name] UNION ALL
		SELECT 'Mamert' AS [Name] UNION ALL
		SELECT 'Manfred' AS [Name] UNION ALL
		SELECT 'Manuel' AS [Name] UNION ALL
		SELECT 'Marcel' AS [Name] UNION ALL
		SELECT 'Marceli' AS [Name] UNION ALL
		SELECT 'Marcin' AS [Name] UNION ALL
		SELECT 'Marcjan' AS [Name] UNION ALL
		SELECT 'Marek' AS [Name] UNION ALL
		SELECT 'Marian' AS [Name] UNION ALL
		SELECT 'Marin' AS [Name] UNION ALL
		SELECT 'Mariusz' AS [Name] UNION ALL
		SELECT 'Maryn' AS [Name] UNION ALL
		SELECT 'Mateusz' AS [Name] UNION ALL
		SELECT 'Maurycjusz' AS [Name] UNION ALL
		SELECT 'Maurycy' AS [Name] UNION ALL
		SELECT 'Maurycjusz' AS [Name] UNION ALL
		SELECT 'Medard' AS [Name] UNION ALL
		SELECT 'Melchior' AS [Name] UNION ALL
		SELECT 'Metody' AS [Name] UNION ALL
		SELECT 'Michał' AS [Name] UNION ALL
		SELECT 'Mieszko' AS [Name] UNION ALL
		SELECT 'Mieczysław' AS [Name] UNION ALL
		SELECT 'Mikołaj' AS [Name] UNION ALL
		SELECT 'Milan' AS [Name] UNION ALL
		SELECT 'Miłobąd' AS [Name] UNION ALL
		SELECT 'Miłogost' AS [Name] UNION ALL
		SELECT 'Miłomir' AS [Name] UNION ALL
		SELECT 'Miłorad' AS [Name] UNION ALL
		SELECT 'Miłosław' AS [Name] UNION ALL
		SELECT 'Miłosz' AS [Name] UNION ALL
		SELECT 'Miłowan' AS [Name] UNION ALL
		SELECT 'Miłowit' AS [Name] UNION ALL
		SELECT 'Mirod' AS [Name] UNION ALL
		SELECT 'Miroład' AS [Name] UNION ALL
		SELECT 'Miron' AS [Name] UNION ALL
		SELECT 'Mirosław' AS [Name] UNION ALL
		SELECT 'Mirosz' AS [Name] UNION ALL
		SELECT 'Modest' AS [Name] UNION ALL
		SELECT 'Mojmierz' AS [Name] UNION ALL
		SELECT 'Mojmir' AS [Name] UNION ALL
		SELECT 'Mojżesz' AS [Name] UNION ALL
		SELECT 'Mściwoj' AS [Name] UNION ALL
		SELECT 'Murat' AS [Name] UNION ALL
		SELECT 'Myślimir' AS [Name] UNION ALL
		SELECT 'N' AS [Name] UNION ALL
		SELECT 'Napoleon' AS [Name] UNION ALL
		SELECT 'Narcyz' AS [Name] UNION ALL
		SELECT 'Nasif' AS [Name] UNION ALL
		SELECT 'Natan' AS [Name] UNION ALL
		SELECT 'Natanael' AS [Name] UNION ALL
		SELECT 'Nataniel' AS [Name] UNION ALL
		SELECT 'Nestor' AS [Name] UNION ALL
		SELECT 'Nicefor' AS [Name] UNION ALL
		SELECT 'Niecisław' AS [Name] UNION ALL
		SELECT 'Nikodem' AS [Name] UNION ALL
		SELECT 'Norbert' AS [Name] UNION ALL
		SELECT 'Norman' AS [Name] UNION ALL
		SELECT 'O' AS [Name] UNION ALL
		SELECT 'Odo' AS [Name] UNION ALL
		SELECT 'Odon' AS [Name] UNION ALL
		SELECT 'Oktawian' AS [Name] UNION ALL
		SELECT 'Oktawiusz' AS [Name] UNION ALL
		SELECT 'Olaf' AS [Name] UNION ALL
		SELECT 'Oleg' AS [Name] UNION ALL
		SELECT 'Olgierd' AS [Name] UNION ALL
		SELECT 'Omar' AS [Name] UNION ALL
		SELECT 'Onufry' AS [Name] UNION ALL
		SELECT 'Oskar' AS [Name] UNION ALL
		SELECT 'Orian' AS [Name] UNION ALL
		SELECT 'Otniel' AS [Name] UNION ALL
		SELECT 'Oswald' AS [Name] UNION ALL
		SELECT 'Otokar' AS [Name] UNION ALL
		SELECT 'Otto' AS [Name] UNION ALL
		SELECT 'Otton' AS [Name] UNION ALL
		SELECT 'Owidiusz' AS [Name] UNION ALL
		SELECT 'Ozeasz' AS [Name] UNION ALL
		SELECT 'P' AS [Name] UNION ALL
		SELECT 'Pabian' AS [Name] UNION ALL
		SELECT 'Pachomiusz' AS [Name] UNION ALL
		SELECT 'Pafnucy' AS [Name] UNION ALL
		SELECT 'Pakosław' AS [Name] UNION ALL
		SELECT 'Pankracy' AS [Name] UNION ALL
		SELECT 'Paskal' AS [Name] UNION ALL
		SELECT 'Patrycjusz' AS [Name] UNION ALL
		SELECT 'Patryk' AS [Name] UNION ALL
		SELECT 'Paweł' AS [Name] UNION ALL
		SELECT 'Pelagiusz' AS [Name] UNION ALL
		SELECT 'Petroniusz' AS [Name] UNION ALL
		SELECT 'Piotr' AS [Name] UNION ALL
		SELECT 'Placyd' AS [Name] UNION ALL
		SELECT 'Polikarp' AS [Name] UNION ALL
		SELECT 'Prokop' AS [Name] UNION ALL
		SELECT 'Prot' AS [Name] UNION ALL
		SELECT 'Protazy' AS [Name] UNION ALL
		SELECT 'Przemysł' AS [Name] UNION ALL
		SELECT 'Przemysław' AS [Name] UNION ALL
		SELECT 'Przedpełk' AS [Name] UNION ALL
		SELECT 'Przybysław' AS [Name] UNION ALL
		SELECT 'R' AS [Name] UNION ALL
		SELECT 'Radogost' AS [Name] UNION ALL
		SELECT 'Radomił' AS [Name] UNION ALL
		SELECT 'Radomir' AS [Name] UNION ALL
		SELECT 'Radosław' AS [Name] UNION ALL
		SELECT 'Radowit' AS [Name] UNION ALL
		SELECT 'Radzimir' AS [Name] UNION ALL
		SELECT 'Rafał' AS [Name] UNION ALL
		SELECT 'Rajmund' AS [Name] UNION ALL
		SELECT 'Rajner' AS [Name] UNION ALL
		SELECT 'Randoald' AS [Name] UNION ALL
		SELECT 'Remigiusz' AS [Name] UNION ALL
		SELECT 'Renat' AS [Name] UNION ALL
		SELECT 'Richariusz' AS [Name] UNION ALL
		SELECT 'Robert' AS [Name] UNION ALL
		SELECT 'Roch' AS [Name] UNION ALL
		SELECT 'Roderyk' AS [Name] UNION ALL
		SELECT 'Roland' AS [Name] UNION ALL
		SELECT 'Roman' AS [Name] UNION ALL
		SELECT 'Romuald' AS [Name] UNION ALL
		SELECT 'Ronald' AS [Name] UNION ALL
		SELECT 'Rosłan' AS [Name] UNION ALL
		SELECT 'Rudolf' AS [Name] UNION ALL
		SELECT 'Rufus' AS [Name] UNION ALL
		SELECT 'Ryszard' AS [Name] UNION ALL
		SELECT 'S' AS [Name] UNION ALL
		SELECT 'Salomon' AS [Name] UNION ALL
		SELECT 'Samir' AS [Name] UNION ALL
		SELECT 'Sambor' AS [Name] UNION ALL
		SELECT 'Samson' AS [Name] UNION ALL
		SELECT 'Samuel' AS [Name] UNION ALL
		SELECT 'Sebastian' AS [Name] UNION ALL
		SELECT 'Serafin' AS [Name] UNION ALL
		SELECT 'Sergiusz' AS [Name] UNION ALL
		SELECT 'Serwacy' AS [Name] UNION ALL
		SELECT 'Seweryn' AS [Name] UNION ALL
		SELECT 'Sędomir' AS [Name] UNION ALL
		SELECT 'Sędzisław' AS [Name] UNION ALL
		SELECT 'Siemowit' AS [Name] UNION ALL
		SELECT 'Skałosz' AS [Name] UNION ALL
		SELECT 'Sław' AS [Name] UNION ALL
		SELECT 'Sławek' AS [Name] UNION ALL
		SELECT 'Sławomierz' AS [Name] UNION ALL
		SELECT 'Sławomir' AS [Name] UNION ALL
		SELECT 'Sobiesław' AS [Name] UNION ALL
		SELECT 'Sofroniusz' AS [Name] UNION ALL
		SELECT 'Stanisław' AS [Name] UNION ALL
		SELECT 'Starwit' AS [Name] UNION ALL
		SELECT 'Stefan' AS [Name] UNION ALL
		SELECT 'Stoigniew' AS [Name] UNION ALL
		SELECT 'Stoisław' AS [Name] UNION ALL
		SELECT 'Stojan' AS [Name] UNION ALL
		SELECT 'Strzeżymir' AS [Name] UNION ALL
		SELECT 'Subisław' AS [Name] UNION ALL
		SELECT 'Sulibor' AS [Name] UNION ALL
		SELECT 'Sulisław' AS [Name] UNION ALL
		SELECT 'Sydoniusz' AS [Name] UNION ALL
		SELECT 'Sykstus' AS [Name] UNION ALL
		SELECT 'Sylwan' AS [Name] UNION ALL
		SELECT 'Sylwester' AS [Name] UNION ALL
		SELECT 'Sylwiusz' AS [Name] UNION ALL
		SELECT 'Symeon' AS [Name] UNION ALL
		SELECT 'Symplicjusz' AS [Name] UNION ALL
		SELECT 'Syriusz' AS [Name] UNION ALL
		SELECT 'Szczepan' AS [Name] UNION ALL
		SELECT 'Szymon' AS [Name] UNION ALL
		SELECT 'Ś' AS [Name] UNION ALL
		SELECT 'Świętibor' AS [Name] UNION ALL
		SELECT 'Świętomir' AS [Name] UNION ALL
		SELECT 'Świętopełk' AS [Name] UNION ALL
		SELECT 'Świętosław' AS [Name] UNION ALL
		SELECT 'T' AS [Name] UNION ALL
		SELECT 'Tadeusz' AS [Name] UNION ALL
		SELECT 'Tarik' AS [Name] UNION ALL
		SELECT 'Telesfor' AS [Name] UNION ALL
		SELECT 'Teobald' AS [Name] UNION ALL
		SELECT 'Teodor' AS [Name] UNION ALL
		SELECT 'Teodozjusz' AS [Name] UNION ALL
		SELECT 'Teofil' AS [Name] UNION ALL
		SELECT 'Tęgomir' AS [Name] UNION ALL
		SELECT 'Tobiasz' AS [Name] UNION ALL
		SELECT 'Tomasz' AS [Name] UNION ALL
		SELECT 'Tomisław' AS [Name] UNION ALL
		SELECT 'Tristan' AS [Name] UNION ALL
		SELECT 'Tulimir' AS [Name] UNION ALL
		SELECT 'Tulimierz' AS [Name] UNION ALL
		SELECT 'Tyberiusz' AS [Name] UNION ALL
		SELECT 'Tymon' AS [Name] UNION ALL
		SELECT 'Tymoteusz' AS [Name] UNION ALL
		SELECT 'Tytus' AS [Name] UNION ALL
		SELECT 'U' AS [Name] UNION ALL
		SELECT 'Urban' AS [Name] UNION ALL
		SELECT 'Ursyn' AS [Name] UNION ALL
		SELECT 'W' AS [Name] UNION ALL
		SELECT 'Wacław' AS [Name] UNION ALL
		SELECT 'Wahid' AS [Name] UNION ALL
		SELECT 'Waldemar' AS [Name] UNION ALL
		SELECT 'Walenty' AS [Name] UNION ALL
		SELECT 'Walentyn' AS [Name] UNION ALL
		SELECT 'Walerian' AS [Name] UNION ALL
		SELECT 'Walery' AS [Name] UNION ALL
		SELECT 'Walter' AS [Name] UNION ALL
		SELECT 'Wandelin' AS [Name] UNION ALL
		SELECT 'Waryn' AS [Name] UNION ALL
		SELECT 'Wawrzyniec' AS [Name] UNION ALL
		SELECT 'Więcesław' AS [Name] UNION ALL
		SELECT 'Wenancjusz' AS [Name] UNION ALL
		SELECT 'Wespazjan' AS [Name] UNION ALL
		SELECT 'Wielisław' AS [Name] UNION ALL
		SELECT 'Wiesław' AS [Name] UNION ALL
		SELECT 'Wiktor' AS [Name] UNION ALL
		SELECT 'Wilhelm' AS [Name] UNION ALL
		SELECT 'Wincenty' AS [Name] UNION ALL
		SELECT 'Wirgiliusz' AS [Name] UNION ALL
		SELECT 'Wirginiusz' AS [Name] UNION ALL
		SELECT 'Wisław' AS [Name] UNION ALL
		SELECT 'Wit' AS [Name] UNION ALL
		SELECT 'Witold' AS [Name] UNION ALL
		SELECT 'Witołd' AS [Name] UNION ALL
		SELECT 'Witosław' AS [Name] UNION ALL
		SELECT 'Władysław' AS [Name] UNION ALL
		SELECT 'Włodzimierz' AS [Name] UNION ALL
		SELECT 'Włodzisław' AS [Name] UNION ALL
		SELECT 'Wojciech' AS [Name] UNION ALL
		SELECT 'Wolimir' AS [Name] UNION ALL
		SELECT 'Wojsław' AS [Name] UNION ALL
		SELECT 'Wrocisław' AS [Name] UNION ALL
		SELECT 'Wszebor' AS [Name] UNION ALL
		SELECT 'Z' AS [Name] UNION ALL
		SELECT 'Zachariasz' AS [Name] UNION ALL
		SELECT 'Zbigniew' AS [Name] UNION ALL
		SELECT 'Zdzisław' AS [Name] UNION ALL
		SELECT 'Zenobiusz' AS [Name] UNION ALL
		SELECT 'Zefiryn' AS [Name] UNION ALL
		SELECT 'Zenon' AS [Name] UNION ALL
		SELECT 'Ziemowit' AS [Name] UNION ALL
		SELECT 'Zwinisław' AS [Name] UNION ALL
		SELECT 'Zygbert' AS [Name] UNION ALL
		SELECT 'Zygfryd' AS [Name] UNION ALL
		SELECT 'Zygmunt'
	) AS Pom
	WHERE LEN(Pom.[Name]) > 1

	--IF NOT EXISTS (SELECT * FROM [dbo].[User])
	--INSERT INTO [User] ([Name])
	--SELECT * FROM 


CATCH

END TRY